/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.profissional;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Academico</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.profissional.ProfissionalPackage#getAcademico()
 * @model
 * @generated
 */
public interface Academico extends Type
{
} // Academico
