/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.profissional.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.profissional.Academico;
import org.xtext.example.mydsl.profissional.ProfissionalPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Academico</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AcademicoImpl extends TypeImpl implements Academico
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AcademicoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ProfissionalPackage.Literals.ACADEMICO;
  }

} //AcademicoImpl
