/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.profissional.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.profissional.Empresa;
import org.xtext.example.mydsl.profissional.ProfissionalPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Empresa</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EmpresaImpl extends TypeImpl implements Empresa
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EmpresaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ProfissionalPackage.Literals.EMPRESA;
  }

} //EmpresaImpl
