/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.profissional.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.mydsl.profissional.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ProfissionalFactoryImpl extends EFactoryImpl implements ProfissionalFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static ProfissionalFactory init()
  {
    try
    {
      ProfissionalFactory theProfissionalFactory = (ProfissionalFactory)EPackage.Registry.INSTANCE.getEFactory(ProfissionalPackage.eNS_URI);
      if (theProfissionalFactory != null)
      {
        return theProfissionalFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new ProfissionalFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProfissionalFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case ProfissionalPackage.MODEL: return createModel();
      case ProfissionalPackage.TYPE: return createType();
      case ProfissionalPackage.ACADEMICO: return createAcademico();
      case ProfissionalPackage.EMPRESA: return createEmpresa();
      case ProfissionalPackage.LINGUAGENS: return createLinguagens();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Type createType()
  {
    TypeImpl type = new TypeImpl();
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Academico createAcademico()
  {
    AcademicoImpl academico = new AcademicoImpl();
    return academico;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Empresa createEmpresa()
  {
    EmpresaImpl empresa = new EmpresaImpl();
    return empresa;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Linguagens createLinguagens()
  {
    LinguagensImpl linguagens = new LinguagensImpl();
    return linguagens;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ProfissionalPackage getProfissionalPackage()
  {
    return (ProfissionalPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static ProfissionalPackage getPackage()
  {
    return ProfissionalPackage.eINSTANCE;
  }

} //ProfissionalFactoryImpl
