/*
 * generated by Xtext 2.25.0
 */
grammar InternalProfissional;

options {
	superClass=AbstractInternalContentAssistParser;
}

@lexer::header {
package org.xtext.example.mydsl.ide.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package org.xtext.example.mydsl.ide.contentassist.antlr.internal;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import org.xtext.example.mydsl.services.ProfissionalGrammarAccess;

}
@parser::members {
	private ProfissionalGrammarAccess grammarAccess;

	public void setGrammarAccess(ProfissionalGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		return tokenName;
	}
}

// Entry rule entryRuleModel
entryRuleModel
:
{ before(grammarAccess.getModelRule()); }
	 ruleModel
{ after(grammarAccess.getModelRule()); } 
	 EOF 
;

// Rule Model
ruleModel 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getModelAccess().getProfissionalAssignment()); }
		(rule__Model__ProfissionalAssignment)*
		{ after(grammarAccess.getModelAccess().getProfissionalAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleType
entryRuleType
:
{ before(grammarAccess.getTypeRule()); }
	 ruleType
{ after(grammarAccess.getTypeRule()); } 
	 EOF 
;

// Rule Type
ruleType 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getTypeAccess().getAlternatives()); }
		(rule__Type__Alternatives)
		{ after(grammarAccess.getTypeAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleAcademico
entryRuleAcademico
:
{ before(grammarAccess.getAcademicoRule()); }
	 ruleAcademico
{ after(grammarAccess.getAcademicoRule()); } 
	 EOF 
;

// Rule Academico
ruleAcademico 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getAcademicoAccess().getGroup()); }
		(rule__Academico__Group__0)
		{ after(grammarAccess.getAcademicoAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEmpresa
entryRuleEmpresa
:
{ before(grammarAccess.getEmpresaRule()); }
	 ruleEmpresa
{ after(grammarAccess.getEmpresaRule()); } 
	 EOF 
;

// Rule Empresa
ruleEmpresa 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEmpresaAccess().getGroup()); }
		(rule__Empresa__Group__0)
		{ after(grammarAccess.getEmpresaAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleLinguagens
entryRuleLinguagens
:
{ before(grammarAccess.getLinguagensRule()); }
	 ruleLinguagens
{ after(grammarAccess.getLinguagensRule()); } 
	 EOF 
;

// Rule Linguagens
ruleLinguagens 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getLinguagensAccess().getGroup()); }
		(rule__Linguagens__Group__0)
		{ after(grammarAccess.getLinguagensAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Type__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTypeAccess().getAcademicoParserRuleCall_0()); }
		ruleAcademico
		{ after(grammarAccess.getTypeAccess().getAcademicoParserRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getTypeAccess().getEmpresaParserRuleCall_1()); }
		ruleEmpresa
		{ after(grammarAccess.getTypeAccess().getEmpresaParserRuleCall_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Academico__Group__0__Impl
	rule__Academico__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAcademicoAccess().getNomeKeyword_0()); }
	'Nome:'
	{ after(grammarAccess.getAcademicoAccess().getNomeKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Academico__Group__1__Impl
	rule__Academico__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAcademicoAccess().getNameAssignment_1()); }
	(rule__Academico__NameAssignment_1)
	{ after(grammarAccess.getAcademicoAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Academico__Group__2__Impl
	rule__Academico__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAcademicoAccess().getCommaKeyword_2()); }
	','
	{ after(grammarAccess.getAcademicoAccess().getCommaKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Academico__Group__3__Impl
	rule__Academico__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAcademicoAccess().getGroup_3()); }
	(rule__Academico__Group_3__0)?
	{ after(grammarAccess.getAcademicoAccess().getGroup_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Academico__Group__4__Impl
	rule__Academico__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAcademicoAccess().getLattesKeyword_4()); }
	'Lattes:'
	{ after(grammarAccess.getAcademicoAccess().getLattesKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Academico__Group__5__Impl
	rule__Academico__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAcademicoAccess().getNameAssignment_5()); }
	(rule__Academico__NameAssignment_5)
	{ after(grammarAccess.getAcademicoAccess().getNameAssignment_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Academico__Group__6__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAcademicoAccess().getGroup_6()); }
	(rule__Academico__Group_6__0)?
	{ after(grammarAccess.getAcademicoAccess().getGroup_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Academico__Group_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Academico__Group_3__0__Impl
	rule__Academico__Group_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAcademicoAccess().getLinkedinKeyword_3_0()); }
	'Linkedin:'
	{ after(grammarAccess.getAcademicoAccess().getLinkedinKeyword_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Academico__Group_3__1__Impl
	rule__Academico__Group_3__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAcademicoAccess().getNameAssignment_3_1()); }
	(rule__Academico__NameAssignment_3_1)
	{ after(grammarAccess.getAcademicoAccess().getNameAssignment_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group_3__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Academico__Group_3__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group_3__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAcademicoAccess().getCommaKeyword_3_2()); }
	','
	{ after(grammarAccess.getAcademicoAccess().getCommaKeyword_3_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Academico__Group_6__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Academico__Group_6__0__Impl
	rule__Academico__Group_6__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group_6__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAcademicoAccess().getLeftCurlyBracketKeyword_6_0()); }
	'{'
	{ after(grammarAccess.getAcademicoAccess().getLeftCurlyBracketKeyword_6_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group_6__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Academico__Group_6__1__Impl
	rule__Academico__Group_6__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group_6__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAcademicoAccess().getLinguagemAssignment_6_1()); }
	(rule__Academico__LinguagemAssignment_6_1)*
	{ after(grammarAccess.getAcademicoAccess().getLinguagemAssignment_6_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group_6__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Academico__Group_6__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__Group_6__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAcademicoAccess().getRightCurlyBracketKeyword_6_2()); }
	'}'
	{ after(grammarAccess.getAcademicoAccess().getRightCurlyBracketKeyword_6_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Empresa__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Empresa__Group__0__Impl
	rule__Empresa__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEmpresaAccess().getNomeKeyword_0()); }
	'Nome:'
	{ after(grammarAccess.getEmpresaAccess().getNomeKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Empresa__Group__1__Impl
	rule__Empresa__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEmpresaAccess().getNameAssignment_1()); }
	(rule__Empresa__NameAssignment_1)
	{ after(grammarAccess.getEmpresaAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Empresa__Group__2__Impl
	rule__Empresa__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEmpresaAccess().getCommaKeyword_2()); }
	','
	{ after(grammarAccess.getEmpresaAccess().getCommaKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Empresa__Group__3__Impl
	rule__Empresa__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEmpresaAccess().getGroup_3()); }
	(rule__Empresa__Group_3__0)?
	{ after(grammarAccess.getEmpresaAccess().getGroup_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Empresa__Group__4__Impl
	rule__Empresa__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEmpresaAccess().getLinkedinKeyword_4()); }
	'Linkedin:'
	{ after(grammarAccess.getEmpresaAccess().getLinkedinKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Empresa__Group__5__Impl
	rule__Empresa__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEmpresaAccess().getNameAssignment_5()); }
	(rule__Empresa__NameAssignment_5)
	{ after(grammarAccess.getEmpresaAccess().getNameAssignment_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Empresa__Group__6__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEmpresaAccess().getGroup_6()); }
	(rule__Empresa__Group_6__0)?
	{ after(grammarAccess.getEmpresaAccess().getGroup_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Empresa__Group_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Empresa__Group_3__0__Impl
	rule__Empresa__Group_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEmpresaAccess().getLattesKeyword_3_0()); }
	'Lattes:'
	{ after(grammarAccess.getEmpresaAccess().getLattesKeyword_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Empresa__Group_3__1__Impl
	rule__Empresa__Group_3__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEmpresaAccess().getNameAssignment_3_1()); }
	(rule__Empresa__NameAssignment_3_1)
	{ after(grammarAccess.getEmpresaAccess().getNameAssignment_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group_3__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Empresa__Group_3__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group_3__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEmpresaAccess().getCommaKeyword_3_2()); }
	','
	{ after(grammarAccess.getEmpresaAccess().getCommaKeyword_3_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Empresa__Group_6__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Empresa__Group_6__0__Impl
	rule__Empresa__Group_6__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group_6__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEmpresaAccess().getLeftCurlyBracketKeyword_6_0()); }
	'{'
	{ after(grammarAccess.getEmpresaAccess().getLeftCurlyBracketKeyword_6_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group_6__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Empresa__Group_6__1__Impl
	rule__Empresa__Group_6__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group_6__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEmpresaAccess().getLinguagemAssignment_6_1()); }
	(rule__Empresa__LinguagemAssignment_6_1)*
	{ after(grammarAccess.getEmpresaAccess().getLinguagemAssignment_6_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group_6__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Empresa__Group_6__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__Group_6__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEmpresaAccess().getRightCurlyBracketKeyword_6_2()); }
	'}'
	{ after(grammarAccess.getEmpresaAccess().getRightCurlyBracketKeyword_6_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Linguagens__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Linguagens__Group__0__Impl
	rule__Linguagens__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Linguagens__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLinguagensAccess().getNomeDaLinguagemKeyword_0()); }
	'Nome da Linguagem:'
	{ after(grammarAccess.getLinguagensAccess().getNomeDaLinguagemKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Linguagens__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Linguagens__Group__1__Impl
	rule__Linguagens__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Linguagens__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLinguagensAccess().getNameAssignment_1()); }
	(rule__Linguagens__NameAssignment_1)
	{ after(grammarAccess.getLinguagensAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Linguagens__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Linguagens__Group__2__Impl
	rule__Linguagens__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Linguagens__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLinguagensAccess().getCommaKeyword_2()); }
	','
	{ after(grammarAccess.getLinguagensAccess().getCommaKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Linguagens__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Linguagens__Group__3__Impl
	rule__Linguagens__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Linguagens__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLinguagensAccess().getTempoDeExperiNciaKeyword_3()); }
	'Tempo de Experi\u00EAncia:'
	{ after(grammarAccess.getLinguagensAccess().getTempoDeExperiNciaKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Linguagens__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Linguagens__Group__4__Impl
	rule__Linguagens__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Linguagens__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLinguagensAccess().getNameAssignment_4()); }
	(rule__Linguagens__NameAssignment_4)
	{ after(grammarAccess.getLinguagensAccess().getNameAssignment_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Linguagens__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Linguagens__Group__5__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Linguagens__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getLinguagensAccess().getMesesKeyword_5()); }
	'meses'
	{ after(grammarAccess.getLinguagensAccess().getMesesKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Model__ProfissionalAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getProfissionalTypeParserRuleCall_0()); }
		ruleType
		{ after(grammarAccess.getModelAccess().getProfissionalTypeParserRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAcademicoAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getAcademicoAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__NameAssignment_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAcademicoAccess().getNameIDTerminalRuleCall_3_1_0()); }
		RULE_ID
		{ after(grammarAccess.getAcademicoAccess().getNameIDTerminalRuleCall_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__NameAssignment_5
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAcademicoAccess().getNameIDTerminalRuleCall_5_0()); }
		RULE_ID
		{ after(grammarAccess.getAcademicoAccess().getNameIDTerminalRuleCall_5_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Academico__LinguagemAssignment_6_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAcademicoAccess().getLinguagemLinguagensParserRuleCall_6_1_0()); }
		ruleLinguagens
		{ after(grammarAccess.getAcademicoAccess().getLinguagemLinguagensParserRuleCall_6_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEmpresaAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getEmpresaAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__NameAssignment_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEmpresaAccess().getNameIDTerminalRuleCall_3_1_0()); }
		RULE_ID
		{ after(grammarAccess.getEmpresaAccess().getNameIDTerminalRuleCall_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__NameAssignment_5
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEmpresaAccess().getNameIDTerminalRuleCall_5_0()); }
		RULE_ID
		{ after(grammarAccess.getEmpresaAccess().getNameIDTerminalRuleCall_5_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Empresa__LinguagemAssignment_6_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEmpresaAccess().getLinguagemLinguagensParserRuleCall_6_1_0()); }
		ruleLinguagens
		{ after(grammarAccess.getEmpresaAccess().getLinguagemLinguagensParserRuleCall_6_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Linguagens__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getLinguagensAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getLinguagensAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Linguagens__NameAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getLinguagensAccess().getNameIDTerminalRuleCall_4_0()); }
		RULE_ID
		{ after(grammarAccess.getLinguagensAccess().getNameIDTerminalRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

RULE_DIGIT : '0'..'9';

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
