/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.profissional;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.profissional.Model#getProfissional <em>Profissional</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.profissional.ProfissionalPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Profissional</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.profissional.Pessoa}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Profissional</em>' containment reference list.
   * @see org.xtext.example.mydsl.profissional.ProfissionalPackage#getModel_Profissional()
   * @model containment="true"
   * @generated
   */
  EList<Pessoa> getProfissional();

} // Model
