/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.profissional;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pessoa</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.profissional.Pessoa#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.profissional.Pessoa#getEmpresa <em>Empresa</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.profissional.ProfissionalPackage#getPessoa()
 * @model
 * @generated
 */
public interface Pessoa extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.profissional.ProfissionalPackage#getPessoa_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.profissional.Pessoa#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Empresa</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.profissional.Empresa}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Empresa</em>' containment reference list.
   * @see org.xtext.example.mydsl.profissional.ProfissionalPackage#getPessoa_Empresa()
   * @model containment="true"
   * @generated
   */
  EList<Empresa> getEmpresa();

} // Pessoa
