/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.memorando;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cargo Destinatario</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.memorando.CargoDestinatario#getCargoDestinatario <em>Cargo Destinatario</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getCargoDestinatario()
 * @model
 * @generated
 */
public interface CargoDestinatario extends EObject
{
  /**
   * Returns the value of the '<em><b>Cargo Destinatario</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cargo Destinatario</em>' attribute.
   * @see #setCargoDestinatario(String)
   * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getCargoDestinatario_CargoDestinatario()
   * @model
   * @generated
   */
  String getCargoDestinatario();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.memorando.CargoDestinatario#getCargoDestinatario <em>Cargo Destinatario</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cargo Destinatario</em>' attribute.
   * @see #getCargoDestinatario()
   * @generated
   */
  void setCargoDestinatario(String value);

} // CargoDestinatario
