/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.memorando;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Destino</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.memorando.Destino#getDestino <em>Destino</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getDestino()
 * @model
 * @generated
 */
public interface Destino extends EObject
{
  /**
   * Returns the value of the '<em><b>Destino</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Destino</em>' attribute.
   * @see #setDestino(String)
   * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getDestino_Destino()
   * @model
   * @generated
   */
  String getDestino();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.memorando.Destino#getDestino <em>Destino</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Destino</em>' attribute.
   * @see #getDestino()
   * @generated
   */
  void setDestino(String value);

} // Destino
