/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.memorando;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.memorando.MemorandoFactory
 * @model kind="package"
 * @generated
 */
public interface MemorandoPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "memorando";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Memorando";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "memorando";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MemorandoPackage eINSTANCE = org.xtext.example.mydsl.memorando.impl.MemorandoPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.memorando.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.memorando.impl.ModelImpl
   * @see org.xtext.example.mydsl.memorando.impl.MemorandoPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Memorandos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__MEMORANDOS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.memorando.impl.MemorandoImpl <em>Memorando</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.memorando.impl.MemorandoImpl
   * @see org.xtext.example.mydsl.memorando.impl.MemorandoPackageImpl#getMemorando()
   * @generated
   */
  int MEMORANDO = 1;

  /**
   * The feature id for the '<em><b>Numero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORANDO__NUMERO = 0;

  /**
   * The feature id for the '<em><b>Setores Destinatarios</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORANDO__SETORES_DESTINATARIOS = 1;

  /**
   * The feature id for the '<em><b>Setor Remetente</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORANDO__SETOR_REMETENTE = 2;

  /**
   * The feature id for the '<em><b>Cidade</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORANDO__CIDADE = 3;

  /**
   * The feature id for the '<em><b>Estado</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORANDO__ESTADO = 4;

  /**
   * The feature id for the '<em><b>Dia</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORANDO__DIA = 5;

  /**
   * The feature id for the '<em><b>Mes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORANDO__MES = 6;

  /**
   * The feature id for the '<em><b>Ano</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORANDO__ANO = 7;

  /**
   * The feature id for the '<em><b>Cargos Destinatarios</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORANDO__CARGOS_DESTINATARIOS = 8;

  /**
   * The feature id for the '<em><b>Assunto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORANDO__ASSUNTO = 9;

  /**
   * The feature id for the '<em><b>Destinos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORANDO__DESTINOS = 10;

  /**
   * The feature id for the '<em><b>Paragrafos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORANDO__PARAGRAFOS = 11;

  /**
   * The feature id for the '<em><b>Remetente</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORANDO__REMETENTE = 12;

  /**
   * The feature id for the '<em><b>Cargo Remetente</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORANDO__CARGO_REMETENTE = 13;

  /**
   * The number of structural features of the '<em>Memorando</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORANDO_FEATURE_COUNT = 14;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.memorando.impl.DestinoImpl <em>Destino</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.memorando.impl.DestinoImpl
   * @see org.xtext.example.mydsl.memorando.impl.MemorandoPackageImpl#getDestino()
   * @generated
   */
  int DESTINO = 2;

  /**
   * The feature id for the '<em><b>Destino</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESTINO__DESTINO = 0;

  /**
   * The number of structural features of the '<em>Destino</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESTINO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.memorando.impl.ParagrafoImpl <em>Paragrafo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.memorando.impl.ParagrafoImpl
   * @see org.xtext.example.mydsl.memorando.impl.MemorandoPackageImpl#getParagrafo()
   * @generated
   */
  int PARAGRAFO = 3;

  /**
   * The feature id for the '<em><b>Paragrafo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAGRAFO__PARAGRAFO = 0;

  /**
   * The number of structural features of the '<em>Paragrafo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAGRAFO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.memorando.impl.SetorDestinatarioImpl <em>Setor Destinatario</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.memorando.impl.SetorDestinatarioImpl
   * @see org.xtext.example.mydsl.memorando.impl.MemorandoPackageImpl#getSetorDestinatario()
   * @generated
   */
  int SETOR_DESTINATARIO = 4;

  /**
   * The feature id for the '<em><b>Setor Destinatario</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETOR_DESTINATARIO__SETOR_DESTINATARIO = 0;

  /**
   * The number of structural features of the '<em>Setor Destinatario</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETOR_DESTINATARIO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.memorando.impl.CargoDestinatarioImpl <em>Cargo Destinatario</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.memorando.impl.CargoDestinatarioImpl
   * @see org.xtext.example.mydsl.memorando.impl.MemorandoPackageImpl#getCargoDestinatario()
   * @generated
   */
  int CARGO_DESTINATARIO = 5;

  /**
   * The feature id for the '<em><b>Cargo Destinatario</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARGO_DESTINATARIO__CARGO_DESTINATARIO = 0;

  /**
   * The number of structural features of the '<em>Cargo Destinatario</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARGO_DESTINATARIO_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.memorando.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.memorando.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.memorando.Model#getMemorandos <em>Memorandos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Memorandos</em>'.
   * @see org.xtext.example.mydsl.memorando.Model#getMemorandos()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Memorandos();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.memorando.Memorando <em>Memorando</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Memorando</em>'.
   * @see org.xtext.example.mydsl.memorando.Memorando
   * @generated
   */
  EClass getMemorando();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.memorando.Memorando#getNumero <em>Numero</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Numero</em>'.
   * @see org.xtext.example.mydsl.memorando.Memorando#getNumero()
   * @see #getMemorando()
   * @generated
   */
  EAttribute getMemorando_Numero();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.memorando.Memorando#getSetoresDestinatarios <em>Setores Destinatarios</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Setores Destinatarios</em>'.
   * @see org.xtext.example.mydsl.memorando.Memorando#getSetoresDestinatarios()
   * @see #getMemorando()
   * @generated
   */
  EReference getMemorando_SetoresDestinatarios();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.memorando.Memorando#getSetorRemetente <em>Setor Remetente</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Setor Remetente</em>'.
   * @see org.xtext.example.mydsl.memorando.Memorando#getSetorRemetente()
   * @see #getMemorando()
   * @generated
   */
  EAttribute getMemorando_SetorRemetente();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.memorando.Memorando#getCidade <em>Cidade</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cidade</em>'.
   * @see org.xtext.example.mydsl.memorando.Memorando#getCidade()
   * @see #getMemorando()
   * @generated
   */
  EAttribute getMemorando_Cidade();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.memorando.Memorando#getEstado <em>Estado</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Estado</em>'.
   * @see org.xtext.example.mydsl.memorando.Memorando#getEstado()
   * @see #getMemorando()
   * @generated
   */
  EAttribute getMemorando_Estado();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.memorando.Memorando#getDia <em>Dia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dia</em>'.
   * @see org.xtext.example.mydsl.memorando.Memorando#getDia()
   * @see #getMemorando()
   * @generated
   */
  EAttribute getMemorando_Dia();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.memorando.Memorando#getMes <em>Mes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mes</em>'.
   * @see org.xtext.example.mydsl.memorando.Memorando#getMes()
   * @see #getMemorando()
   * @generated
   */
  EAttribute getMemorando_Mes();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.memorando.Memorando#getAno <em>Ano</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ano</em>'.
   * @see org.xtext.example.mydsl.memorando.Memorando#getAno()
   * @see #getMemorando()
   * @generated
   */
  EAttribute getMemorando_Ano();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.memorando.Memorando#getCargosDestinatarios <em>Cargos Destinatarios</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cargos Destinatarios</em>'.
   * @see org.xtext.example.mydsl.memorando.Memorando#getCargosDestinatarios()
   * @see #getMemorando()
   * @generated
   */
  EReference getMemorando_CargosDestinatarios();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.memorando.Memorando#getAssunto <em>Assunto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Assunto</em>'.
   * @see org.xtext.example.mydsl.memorando.Memorando#getAssunto()
   * @see #getMemorando()
   * @generated
   */
  EAttribute getMemorando_Assunto();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.memorando.Memorando#getDestinos <em>Destinos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Destinos</em>'.
   * @see org.xtext.example.mydsl.memorando.Memorando#getDestinos()
   * @see #getMemorando()
   * @generated
   */
  EReference getMemorando_Destinos();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.memorando.Memorando#getParagrafos <em>Paragrafos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Paragrafos</em>'.
   * @see org.xtext.example.mydsl.memorando.Memorando#getParagrafos()
   * @see #getMemorando()
   * @generated
   */
  EReference getMemorando_Paragrafos();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.memorando.Memorando#getRemetente <em>Remetente</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Remetente</em>'.
   * @see org.xtext.example.mydsl.memorando.Memorando#getRemetente()
   * @see #getMemorando()
   * @generated
   */
  EAttribute getMemorando_Remetente();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.memorando.Memorando#getCargoRemetente <em>Cargo Remetente</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cargo Remetente</em>'.
   * @see org.xtext.example.mydsl.memorando.Memorando#getCargoRemetente()
   * @see #getMemorando()
   * @generated
   */
  EAttribute getMemorando_CargoRemetente();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.memorando.Destino <em>Destino</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Destino</em>'.
   * @see org.xtext.example.mydsl.memorando.Destino
   * @generated
   */
  EClass getDestino();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.memorando.Destino#getDestino <em>Destino</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Destino</em>'.
   * @see org.xtext.example.mydsl.memorando.Destino#getDestino()
   * @see #getDestino()
   * @generated
   */
  EAttribute getDestino_Destino();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.memorando.Paragrafo <em>Paragrafo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Paragrafo</em>'.
   * @see org.xtext.example.mydsl.memorando.Paragrafo
   * @generated
   */
  EClass getParagrafo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.memorando.Paragrafo#getParagrafo <em>Paragrafo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Paragrafo</em>'.
   * @see org.xtext.example.mydsl.memorando.Paragrafo#getParagrafo()
   * @see #getParagrafo()
   * @generated
   */
  EAttribute getParagrafo_Paragrafo();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.memorando.SetorDestinatario <em>Setor Destinatario</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Setor Destinatario</em>'.
   * @see org.xtext.example.mydsl.memorando.SetorDestinatario
   * @generated
   */
  EClass getSetorDestinatario();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.memorando.SetorDestinatario#getSetorDestinatario <em>Setor Destinatario</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Setor Destinatario</em>'.
   * @see org.xtext.example.mydsl.memorando.SetorDestinatario#getSetorDestinatario()
   * @see #getSetorDestinatario()
   * @generated
   */
  EAttribute getSetorDestinatario_SetorDestinatario();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.memorando.CargoDestinatario <em>Cargo Destinatario</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cargo Destinatario</em>'.
   * @see org.xtext.example.mydsl.memorando.CargoDestinatario
   * @generated
   */
  EClass getCargoDestinatario();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.memorando.CargoDestinatario#getCargoDestinatario <em>Cargo Destinatario</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cargo Destinatario</em>'.
   * @see org.xtext.example.mydsl.memorando.CargoDestinatario#getCargoDestinatario()
   * @see #getCargoDestinatario()
   * @generated
   */
  EAttribute getCargoDestinatario_CargoDestinatario();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MemorandoFactory getMemorandoFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.memorando.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.memorando.impl.ModelImpl
     * @see org.xtext.example.mydsl.memorando.impl.MemorandoPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Memorandos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__MEMORANDOS = eINSTANCE.getModel_Memorandos();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.memorando.impl.MemorandoImpl <em>Memorando</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.memorando.impl.MemorandoImpl
     * @see org.xtext.example.mydsl.memorando.impl.MemorandoPackageImpl#getMemorando()
     * @generated
     */
    EClass MEMORANDO = eINSTANCE.getMemorando();

    /**
     * The meta object literal for the '<em><b>Numero</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEMORANDO__NUMERO = eINSTANCE.getMemorando_Numero();

    /**
     * The meta object literal for the '<em><b>Setores Destinatarios</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MEMORANDO__SETORES_DESTINATARIOS = eINSTANCE.getMemorando_SetoresDestinatarios();

    /**
     * The meta object literal for the '<em><b>Setor Remetente</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEMORANDO__SETOR_REMETENTE = eINSTANCE.getMemorando_SetorRemetente();

    /**
     * The meta object literal for the '<em><b>Cidade</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEMORANDO__CIDADE = eINSTANCE.getMemorando_Cidade();

    /**
     * The meta object literal for the '<em><b>Estado</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEMORANDO__ESTADO = eINSTANCE.getMemorando_Estado();

    /**
     * The meta object literal for the '<em><b>Dia</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEMORANDO__DIA = eINSTANCE.getMemorando_Dia();

    /**
     * The meta object literal for the '<em><b>Mes</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEMORANDO__MES = eINSTANCE.getMemorando_Mes();

    /**
     * The meta object literal for the '<em><b>Ano</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEMORANDO__ANO = eINSTANCE.getMemorando_Ano();

    /**
     * The meta object literal for the '<em><b>Cargos Destinatarios</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MEMORANDO__CARGOS_DESTINATARIOS = eINSTANCE.getMemorando_CargosDestinatarios();

    /**
     * The meta object literal for the '<em><b>Assunto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEMORANDO__ASSUNTO = eINSTANCE.getMemorando_Assunto();

    /**
     * The meta object literal for the '<em><b>Destinos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MEMORANDO__DESTINOS = eINSTANCE.getMemorando_Destinos();

    /**
     * The meta object literal for the '<em><b>Paragrafos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MEMORANDO__PARAGRAFOS = eINSTANCE.getMemorando_Paragrafos();

    /**
     * The meta object literal for the '<em><b>Remetente</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEMORANDO__REMETENTE = eINSTANCE.getMemorando_Remetente();

    /**
     * The meta object literal for the '<em><b>Cargo Remetente</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEMORANDO__CARGO_REMETENTE = eINSTANCE.getMemorando_CargoRemetente();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.memorando.impl.DestinoImpl <em>Destino</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.memorando.impl.DestinoImpl
     * @see org.xtext.example.mydsl.memorando.impl.MemorandoPackageImpl#getDestino()
     * @generated
     */
    EClass DESTINO = eINSTANCE.getDestino();

    /**
     * The meta object literal for the '<em><b>Destino</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESTINO__DESTINO = eINSTANCE.getDestino_Destino();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.memorando.impl.ParagrafoImpl <em>Paragrafo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.memorando.impl.ParagrafoImpl
     * @see org.xtext.example.mydsl.memorando.impl.MemorandoPackageImpl#getParagrafo()
     * @generated
     */
    EClass PARAGRAFO = eINSTANCE.getParagrafo();

    /**
     * The meta object literal for the '<em><b>Paragrafo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAGRAFO__PARAGRAFO = eINSTANCE.getParagrafo_Paragrafo();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.memorando.impl.SetorDestinatarioImpl <em>Setor Destinatario</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.memorando.impl.SetorDestinatarioImpl
     * @see org.xtext.example.mydsl.memorando.impl.MemorandoPackageImpl#getSetorDestinatario()
     * @generated
     */
    EClass SETOR_DESTINATARIO = eINSTANCE.getSetorDestinatario();

    /**
     * The meta object literal for the '<em><b>Setor Destinatario</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SETOR_DESTINATARIO__SETOR_DESTINATARIO = eINSTANCE.getSetorDestinatario_SetorDestinatario();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.memorando.impl.CargoDestinatarioImpl <em>Cargo Destinatario</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.memorando.impl.CargoDestinatarioImpl
     * @see org.xtext.example.mydsl.memorando.impl.MemorandoPackageImpl#getCargoDestinatario()
     * @generated
     */
    EClass CARGO_DESTINATARIO = eINSTANCE.getCargoDestinatario();

    /**
     * The meta object literal for the '<em><b>Cargo Destinatario</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARGO_DESTINATARIO__CARGO_DESTINATARIO = eINSTANCE.getCargoDestinatario_CargoDestinatario();

  }

} //MemorandoPackage
