/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.memorando;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Memorando</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.memorando.Memorando#getNumero <em>Numero</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.memorando.Memorando#getSetoresDestinatarios <em>Setores Destinatarios</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.memorando.Memorando#getSetorRemetente <em>Setor Remetente</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.memorando.Memorando#getCidade <em>Cidade</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.memorando.Memorando#getEstado <em>Estado</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.memorando.Memorando#getDia <em>Dia</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.memorando.Memorando#getMes <em>Mes</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.memorando.Memorando#getAno <em>Ano</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.memorando.Memorando#getCargosDestinatarios <em>Cargos Destinatarios</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.memorando.Memorando#getAssunto <em>Assunto</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.memorando.Memorando#getParagrafos <em>Paragrafos</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.memorando.Memorando#getRemetente <em>Remetente</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.memorando.Memorando#getCargoRemetente <em>Cargo Remetente</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getMemorando()
 * @model
 * @generated
 */
public interface Memorando extends EObject
{
  /**
   * Returns the value of the '<em><b>Numero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Numero</em>' attribute.
   * @see #setNumero(int)
   * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getMemorando_Numero()
   * @model
   * @generated
   */
  int getNumero();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.memorando.Memorando#getNumero <em>Numero</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Numero</em>' attribute.
   * @see #getNumero()
   * @generated
   */
  void setNumero(int value);

  /**
   * Returns the value of the '<em><b>Setores Destinatarios</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.memorando.SetorDestinatario}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Setores Destinatarios</em>' containment reference list.
   * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getMemorando_SetoresDestinatarios()
   * @model containment="true"
   * @generated
   */
  EList<SetorDestinatario> getSetoresDestinatarios();

  /**
   * Returns the value of the '<em><b>Setor Remetente</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Setor Remetente</em>' attribute.
   * @see #setSetorRemetente(String)
   * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getMemorando_SetorRemetente()
   * @model
   * @generated
   */
  String getSetorRemetente();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.memorando.Memorando#getSetorRemetente <em>Setor Remetente</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Setor Remetente</em>' attribute.
   * @see #getSetorRemetente()
   * @generated
   */
  void setSetorRemetente(String value);

  /**
   * Returns the value of the '<em><b>Cidade</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cidade</em>' attribute.
   * @see #setCidade(String)
   * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getMemorando_Cidade()
   * @model
   * @generated
   */
  String getCidade();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.memorando.Memorando#getCidade <em>Cidade</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cidade</em>' attribute.
   * @see #getCidade()
   * @generated
   */
  void setCidade(String value);

  /**
   * Returns the value of the '<em><b>Estado</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Estado</em>' attribute.
   * @see #setEstado(String)
   * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getMemorando_Estado()
   * @model
   * @generated
   */
  String getEstado();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.memorando.Memorando#getEstado <em>Estado</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Estado</em>' attribute.
   * @see #getEstado()
   * @generated
   */
  void setEstado(String value);

  /**
   * Returns the value of the '<em><b>Dia</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dia</em>' attribute.
   * @see #setDia(int)
   * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getMemorando_Dia()
   * @model
   * @generated
   */
  int getDia();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.memorando.Memorando#getDia <em>Dia</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dia</em>' attribute.
   * @see #getDia()
   * @generated
   */
  void setDia(int value);

  /**
   * Returns the value of the '<em><b>Mes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mes</em>' attribute.
   * @see #setMes(String)
   * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getMemorando_Mes()
   * @model
   * @generated
   */
  String getMes();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.memorando.Memorando#getMes <em>Mes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mes</em>' attribute.
   * @see #getMes()
   * @generated
   */
  void setMes(String value);

  /**
   * Returns the value of the '<em><b>Ano</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ano</em>' attribute.
   * @see #setAno(int)
   * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getMemorando_Ano()
   * @model
   * @generated
   */
  int getAno();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.memorando.Memorando#getAno <em>Ano</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ano</em>' attribute.
   * @see #getAno()
   * @generated
   */
  void setAno(int value);

  /**
   * Returns the value of the '<em><b>Cargos Destinatarios</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.memorando.CargoDestinatario}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cargos Destinatarios</em>' containment reference list.
   * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getMemorando_CargosDestinatarios()
   * @model containment="true"
   * @generated
   */
  EList<CargoDestinatario> getCargosDestinatarios();

  /**
   * Returns the value of the '<em><b>Assunto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assunto</em>' attribute.
   * @see #setAssunto(String)
   * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getMemorando_Assunto()
   * @model
   * @generated
   */
  String getAssunto();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.memorando.Memorando#getAssunto <em>Assunto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assunto</em>' attribute.
   * @see #getAssunto()
   * @generated
   */
  void setAssunto(String value);

  /**
   * Returns the value of the '<em><b>Paragrafos</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.memorando.Paragrafo}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Paragrafos</em>' containment reference list.
   * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getMemorando_Paragrafos()
   * @model containment="true"
   * @generated
   */
  EList<Paragrafo> getParagrafos();

  /**
   * Returns the value of the '<em><b>Remetente</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Remetente</em>' attribute.
   * @see #setRemetente(String)
   * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getMemorando_Remetente()
   * @model
   * @generated
   */
  String getRemetente();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.memorando.Memorando#getRemetente <em>Remetente</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Remetente</em>' attribute.
   * @see #getRemetente()
   * @generated
   */
  void setRemetente(String value);

  /**
   * Returns the value of the '<em><b>Cargo Remetente</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cargo Remetente</em>' attribute.
   * @see #setCargoRemetente(String)
   * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getMemorando_CargoRemetente()
   * @model
   * @generated
   */
  String getCargoRemetente();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.memorando.Memorando#getCargoRemetente <em>Cargo Remetente</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cargo Remetente</em>' attribute.
   * @see #getCargoRemetente()
   * @generated
   */
  void setCargoRemetente(String value);

} // Memorando
