/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.memorando;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.memorando.Model#getMemorandos <em>Memorandos</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Memorandos</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.memorando.Memorando}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Memorandos</em>' containment reference list.
   * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getModel_Memorandos()
   * @model containment="true"
   * @generated
   */
  EList<Memorando> getMemorandos();

} // Model
