/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.memorando;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Paragrafo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.memorando.Paragrafo#getParagrafo <em>Paragrafo</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getParagrafo()
 * @model
 * @generated
 */
public interface Paragrafo extends EObject
{
  /**
   * Returns the value of the '<em><b>Paragrafo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Paragrafo</em>' attribute.
   * @see #setParagrafo(String)
   * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getParagrafo_Paragrafo()
   * @model
   * @generated
   */
  String getParagrafo();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.memorando.Paragrafo#getParagrafo <em>Paragrafo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Paragrafo</em>' attribute.
   * @see #getParagrafo()
   * @generated
   */
  void setParagrafo(String value);

} // Paragrafo
