/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.memorando;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Setor Destinatario</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.memorando.SetorDestinatario#getSetorDestinatario <em>Setor Destinatario</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getSetorDestinatario()
 * @model
 * @generated
 */
public interface SetorDestinatario extends EObject
{
  /**
   * Returns the value of the '<em><b>Setor Destinatario</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Setor Destinatario</em>' attribute.
   * @see #setSetorDestinatario(String)
   * @see org.xtext.example.mydsl.memorando.MemorandoPackage#getSetorDestinatario_SetorDestinatario()
   * @model
   * @generated
   */
  String getSetorDestinatario();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.memorando.SetorDestinatario#getSetorDestinatario <em>Setor Destinatario</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Setor Destinatario</em>' attribute.
   * @see #getSetorDestinatario()
   * @generated
   */
  void setSetorDestinatario(String value);

} // SetorDestinatario
