/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMemorandoParser;
import org.xtext.example.mydsl.services.MemorandoGrammarAccess;

public class MemorandoParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MemorandoGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MemorandoGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getMemorandoAccess().getGroup(), "rule__Memorando__Group__0");
			builder.put(grammarAccess.getModelAccess().getMemorandosAssignment(), "rule__Model__MemorandosAssignment");
			builder.put(grammarAccess.getMemorandoAccess().getNumeroAssignment_1(), "rule__Memorando__NumeroAssignment_1");
			builder.put(grammarAccess.getMemorandoAccess().getSetorDestinatarioAssignment_3(), "rule__Memorando__SetorDestinatarioAssignment_3");
			builder.put(grammarAccess.getMemorandoAccess().getSetorRemetenteAssignment_5(), "rule__Memorando__SetorRemetenteAssignment_5");
			builder.put(grammarAccess.getMemorandoAccess().getCidadeAssignment_7(), "rule__Memorando__CidadeAssignment_7");
			builder.put(grammarAccess.getMemorandoAccess().getEstadoAssignment_9(), "rule__Memorando__EstadoAssignment_9");
			builder.put(grammarAccess.getMemorandoAccess().getDiaAssignment_11(), "rule__Memorando__DiaAssignment_11");
			builder.put(grammarAccess.getMemorandoAccess().getMesAssignment_13(), "rule__Memorando__MesAssignment_13");
			builder.put(grammarAccess.getMemorandoAccess().getAnoAssignment_15(), "rule__Memorando__AnoAssignment_15");
			builder.put(grammarAccess.getMemorandoAccess().getCargoDestinatarioAssignment_17(), "rule__Memorando__CargoDestinatarioAssignment_17");
			builder.put(grammarAccess.getMemorandoAccess().getAssuntoAssignment_19(), "rule__Memorando__AssuntoAssignment_19");
			builder.put(grammarAccess.getMemorandoAccess().getDestinosAssignment_21(), "rule__Memorando__DestinosAssignment_21");
			builder.put(grammarAccess.getMemorandoAccess().getParagrafosAssignment_23(), "rule__Memorando__ParagrafosAssignment_23");
			builder.put(grammarAccess.getMemorandoAccess().getRemetenteAssignment_25(), "rule__Memorando__RemetenteAssignment_25");
			builder.put(grammarAccess.getMemorandoAccess().getCargoRemetenteAssignment_27(), "rule__Memorando__CargoRemetenteAssignment_27");
			builder.put(grammarAccess.getDestinoAccess().getDestinoAssignment(), "rule__Destino__DestinoAssignment");
			builder.put(grammarAccess.getParagrafoAccess().getParagrafoAssignment(), "rule__Paragrafo__ParagrafoAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MemorandoGrammarAccess grammarAccess;

	@Override
	protected InternalMemorandoParser createParser() {
		InternalMemorandoParser result = new InternalMemorandoParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MemorandoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MemorandoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
