/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.memorando.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.memorando.CargoDestinatario;
import org.xtext.example.mydsl.memorando.MemorandoPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Cargo Destinatario</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.memorando.impl.CargoDestinatarioImpl#getCargoDestinatario <em>Cargo Destinatario</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CargoDestinatarioImpl extends MinimalEObjectImpl.Container implements CargoDestinatario
{
  /**
   * The default value of the '{@link #getCargoDestinatario() <em>Cargo Destinatario</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCargoDestinatario()
   * @generated
   * @ordered
   */
  protected static final String CARGO_DESTINATARIO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCargoDestinatario() <em>Cargo Destinatario</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCargoDestinatario()
   * @generated
   * @ordered
   */
  protected String cargoDestinatario = CARGO_DESTINATARIO_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CargoDestinatarioImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MemorandoPackage.Literals.CARGO_DESTINATARIO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCargoDestinatario()
  {
    return cargoDestinatario;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCargoDestinatario(String newCargoDestinatario)
  {
    String oldCargoDestinatario = cargoDestinatario;
    cargoDestinatario = newCargoDestinatario;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MemorandoPackage.CARGO_DESTINATARIO__CARGO_DESTINATARIO, oldCargoDestinatario, cargoDestinatario));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MemorandoPackage.CARGO_DESTINATARIO__CARGO_DESTINATARIO:
        return getCargoDestinatario();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MemorandoPackage.CARGO_DESTINATARIO__CARGO_DESTINATARIO:
        setCargoDestinatario((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MemorandoPackage.CARGO_DESTINATARIO__CARGO_DESTINATARIO:
        setCargoDestinatario(CARGO_DESTINATARIO_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MemorandoPackage.CARGO_DESTINATARIO__CARGO_DESTINATARIO:
        return CARGO_DESTINATARIO_EDEFAULT == null ? cargoDestinatario != null : !CARGO_DESTINATARIO_EDEFAULT.equals(cargoDestinatario);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (cargoDestinatario: ");
    result.append(cargoDestinatario);
    result.append(')');
    return result.toString();
  }

} //CargoDestinatarioImpl
