/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.memorando.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.memorando.MemorandoPackage;
import org.xtext.example.mydsl.memorando.Paragrafo;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Paragrafo</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.memorando.impl.ParagrafoImpl#getParagrafo <em>Paragrafo</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ParagrafoImpl extends MinimalEObjectImpl.Container implements Paragrafo
{
  /**
   * The default value of the '{@link #getParagrafo() <em>Paragrafo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParagrafo()
   * @generated
   * @ordered
   */
  protected static final String PARAGRAFO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getParagrafo() <em>Paragrafo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParagrafo()
   * @generated
   * @ordered
   */
  protected String paragrafo = PARAGRAFO_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ParagrafoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MemorandoPackage.Literals.PARAGRAFO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getParagrafo()
  {
    return paragrafo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setParagrafo(String newParagrafo)
  {
    String oldParagrafo = paragrafo;
    paragrafo = newParagrafo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MemorandoPackage.PARAGRAFO__PARAGRAFO, oldParagrafo, paragrafo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MemorandoPackage.PARAGRAFO__PARAGRAFO:
        return getParagrafo();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MemorandoPackage.PARAGRAFO__PARAGRAFO:
        setParagrafo((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MemorandoPackage.PARAGRAFO__PARAGRAFO:
        setParagrafo(PARAGRAFO_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MemorandoPackage.PARAGRAFO__PARAGRAFO:
        return PARAGRAFO_EDEFAULT == null ? paragrafo != null : !PARAGRAFO_EDEFAULT.equals(paragrafo);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (paragrafo: ");
    result.append(paragrafo);
    result.append(')');
    return result.toString();
  }

} //ParagrafoImpl
