/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.memorando.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.memorando.MemorandoPackage;
import org.xtext.example.mydsl.memorando.SetorDestinatario;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Setor Destinatario</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.memorando.impl.SetorDestinatarioImpl#getSetorDestinatario <em>Setor Destinatario</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SetorDestinatarioImpl extends MinimalEObjectImpl.Container implements SetorDestinatario
{
  /**
   * The default value of the '{@link #getSetorDestinatario() <em>Setor Destinatario</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSetorDestinatario()
   * @generated
   * @ordered
   */
  protected static final String SETOR_DESTINATARIO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSetorDestinatario() <em>Setor Destinatario</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSetorDestinatario()
   * @generated
   * @ordered
   */
  protected String setorDestinatario = SETOR_DESTINATARIO_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SetorDestinatarioImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MemorandoPackage.Literals.SETOR_DESTINATARIO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSetorDestinatario()
  {
    return setorDestinatario;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSetorDestinatario(String newSetorDestinatario)
  {
    String oldSetorDestinatario = setorDestinatario;
    setorDestinatario = newSetorDestinatario;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MemorandoPackage.SETOR_DESTINATARIO__SETOR_DESTINATARIO, oldSetorDestinatario, setorDestinatario));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MemorandoPackage.SETOR_DESTINATARIO__SETOR_DESTINATARIO:
        return getSetorDestinatario();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MemorandoPackage.SETOR_DESTINATARIO__SETOR_DESTINATARIO:
        setSetorDestinatario((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MemorandoPackage.SETOR_DESTINATARIO__SETOR_DESTINATARIO:
        setSetorDestinatario(SETOR_DESTINATARIO_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MemorandoPackage.SETOR_DESTINATARIO__SETOR_DESTINATARIO:
        return SETOR_DESTINATARIO_EDEFAULT == null ? setorDestinatario != null : !SETOR_DESTINATARIO_EDEFAULT.equals(setorDestinatario);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (setorDestinatario: ");
    result.append(setorDestinatario);
    result.append(')');
    return result.toString();
  }

} //SetorDestinatarioImpl
