grammar org.xtext.example.mydsl.Profissional with org.eclipse.xtext.common.Terminals

generate profissional "http://www.xtext.org/example/mydsl/Profissional"

Model:
	profissional+=Type*;
	
	
Type:
	Academico | Empresa;
	
Academico:
	'Nome:' name=ID ','
	('Linkedin:' name=ID ',')?
	'Lattes:' name=ID
	('{'
        (linguagem+=Linguagens)*
    '}')?;

Empresa:
	'Nome:' name=ID ','
	('Lattes:' name=ID ',')?
	'Linkedin:' name=ID
	('{'
        (linguagem+=Linguagens)*
    '}')?;

Linguagens:
	'Nome da Linguagem:' name=ID ','
	'Tempo de Experiência:' name=ID 'meses';

terminal DIGIT:
    ('0'..'9');