/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MemorandoGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Memorando.Model");
		private final Assignment cMemorandosAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cMemorandosMemorandoParserRuleCall_0 = (RuleCall)cMemorandosAssignment.eContents().get(0);
		
		//Model:
		//    memorandos+=Memorando*;
		@Override public ParserRule getRule() { return rule; }
		
		//memorandos+=Memorando*
		public Assignment getMemorandosAssignment() { return cMemorandosAssignment; }
		
		//Memorando
		public RuleCall getMemorandosMemorandoParserRuleCall_0() { return cMemorandosMemorandoParserRuleCall_0; }
	}
	public class MemorandoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Memorando.Memorando");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNumeroKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNumeroAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNumeroINTTerminalRuleCall_1_0 = (RuleCall)cNumeroAssignment_1.eContents().get(0);
		private final Keyword cSetorDestinatarioKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSetorDestinatarioAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSetorDestinatarioIDTerminalRuleCall_3_0 = (RuleCall)cSetorDestinatarioAssignment_3.eContents().get(0);
		private final Keyword cSetorRemetenteKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cSetorRemetenteAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cSetorRemetenteIDTerminalRuleCall_5_0 = (RuleCall)cSetorRemetenteAssignment_5.eContents().get(0);
		private final Keyword cCidadeKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cCidadeAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cCidadeIDTerminalRuleCall_7_0 = (RuleCall)cCidadeAssignment_7.eContents().get(0);
		private final Keyword cEstadoKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cEstadoAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cEstadoIDTerminalRuleCall_9_0 = (RuleCall)cEstadoAssignment_9.eContents().get(0);
		private final Keyword cDataKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cDiaAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cDiaINTTerminalRuleCall_11_0 = (RuleCall)cDiaAssignment_11.eContents().get(0);
		private final Keyword cSolidusKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cMesAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cMesIDTerminalRuleCall_13_0 = (RuleCall)cMesAssignment_13.eContents().get(0);
		private final Keyword cSolidusKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Assignment cAnoAssignment_15 = (Assignment)cGroup.eContents().get(15);
		private final RuleCall cAnoINTTerminalRuleCall_15_0 = (RuleCall)cAnoAssignment_15.eContents().get(0);
		private final Keyword cCargoDestinatarioKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cCargoDestinatarioAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cCargoDestinatarioSTRINGTerminalRuleCall_17_0 = (RuleCall)cCargoDestinatarioAssignment_17.eContents().get(0);
		private final Keyword cAssuntoKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Assignment cAssuntoAssignment_19 = (Assignment)cGroup.eContents().get(19);
		private final RuleCall cAssuntoSTRINGTerminalRuleCall_19_0 = (RuleCall)cAssuntoAssignment_19.eContents().get(0);
		private final Keyword cDestinosKeyword_20 = (Keyword)cGroup.eContents().get(20);
		private final Assignment cDestinosAssignment_21 = (Assignment)cGroup.eContents().get(21);
		private final RuleCall cDestinosDestinoParserRuleCall_21_0 = (RuleCall)cDestinosAssignment_21.eContents().get(0);
		private final Keyword cMensagemKeyword_22 = (Keyword)cGroup.eContents().get(22);
		private final Assignment cParagrafosAssignment_23 = (Assignment)cGroup.eContents().get(23);
		private final RuleCall cParagrafosParagrafoParserRuleCall_23_0 = (RuleCall)cParagrafosAssignment_23.eContents().get(0);
		private final Keyword cRemetenteKeyword_24 = (Keyword)cGroup.eContents().get(24);
		private final Assignment cRemetenteAssignment_25 = (Assignment)cGroup.eContents().get(25);
		private final RuleCall cRemetenteSTRINGTerminalRuleCall_25_0 = (RuleCall)cRemetenteAssignment_25.eContents().get(0);
		private final Keyword cCargoRemetenteKeyword_26 = (Keyword)cGroup.eContents().get(26);
		private final Assignment cCargoRemetenteAssignment_27 = (Assignment)cGroup.eContents().get(27);
		private final RuleCall cCargoRemetenteSTRINGTerminalRuleCall_27_0 = (RuleCall)cCargoRemetenteAssignment_27.eContents().get(0);
		
		//Memorando:
		//    "Numero: " + numero=INT +
		//    ", Setor Destinatario: " + setorDestinatario=ID +
		//    ", Setor Remetente: " + setorRemetente=ID +
		//    ", Cidade: " cidade=ID +
		//    ", Estado: " estado=ID +
		//    ", Data: " dia=INT + "/" mes=ID + "/" ano=INT +
		//    ", Cargo Destinatario: " cargoDestinatario=STRING +
		//    ", Assunto: " + assunto=STRING +
		//    ", Destinos: " + (destinos+=Destino*) +
		//    ", Mensagem: " + (paragrafos+=Paragrafo*) +
		//    ", Remetente: " + remetente=STRING +
		//    ", Cargo Remetente: " + cargoRemetente=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//"Numero: " + numero=INT +
		//", Setor Destinatario: " + setorDestinatario=ID +
		//", Setor Remetente: " + setorRemetente=ID +
		//", Cidade: " cidade=ID +
		//", Estado: " estado=ID +
		//", Data: " dia=INT + "/" mes=ID + "/" ano=INT +
		//", Cargo Destinatario: " cargoDestinatario=STRING +
		//", Assunto: " + assunto=STRING +
		//", Destinos: " + (destinos+=Destino*) +
		//", Mensagem: " + (paragrafos+=Paragrafo*) +
		//", Remetente: " + remetente=STRING +
		//", Cargo Remetente: " + cargoRemetente=STRING
		public Group getGroup() { return cGroup; }
		
		//"Numero: " +
		public Keyword getNumeroKeyword_0() { return cNumeroKeyword_0; }
		
		//numero=INT +
		public Assignment getNumeroAssignment_1() { return cNumeroAssignment_1; }
		
		//INT
		public RuleCall getNumeroINTTerminalRuleCall_1_0() { return cNumeroINTTerminalRuleCall_1_0; }
		
		//", Setor Destinatario: " +
		public Keyword getSetorDestinatarioKeyword_2() { return cSetorDestinatarioKeyword_2; }
		
		//setorDestinatario=ID +
		public Assignment getSetorDestinatarioAssignment_3() { return cSetorDestinatarioAssignment_3; }
		
		//ID
		public RuleCall getSetorDestinatarioIDTerminalRuleCall_3_0() { return cSetorDestinatarioIDTerminalRuleCall_3_0; }
		
		//", Setor Remetente: " +
		public Keyword getSetorRemetenteKeyword_4() { return cSetorRemetenteKeyword_4; }
		
		//setorRemetente=ID +
		public Assignment getSetorRemetenteAssignment_5() { return cSetorRemetenteAssignment_5; }
		
		//ID
		public RuleCall getSetorRemetenteIDTerminalRuleCall_5_0() { return cSetorRemetenteIDTerminalRuleCall_5_0; }
		
		//", Cidade: "
		public Keyword getCidadeKeyword_6() { return cCidadeKeyword_6; }
		
		//cidade=ID +
		public Assignment getCidadeAssignment_7() { return cCidadeAssignment_7; }
		
		//ID
		public RuleCall getCidadeIDTerminalRuleCall_7_0() { return cCidadeIDTerminalRuleCall_7_0; }
		
		//", Estado: "
		public Keyword getEstadoKeyword_8() { return cEstadoKeyword_8; }
		
		//estado=ID +
		public Assignment getEstadoAssignment_9() { return cEstadoAssignment_9; }
		
		//ID
		public RuleCall getEstadoIDTerminalRuleCall_9_0() { return cEstadoIDTerminalRuleCall_9_0; }
		
		//", Data: "
		public Keyword getDataKeyword_10() { return cDataKeyword_10; }
		
		//dia=INT +
		public Assignment getDiaAssignment_11() { return cDiaAssignment_11; }
		
		//INT
		public RuleCall getDiaINTTerminalRuleCall_11_0() { return cDiaINTTerminalRuleCall_11_0; }
		
		//"/"
		public Keyword getSolidusKeyword_12() { return cSolidusKeyword_12; }
		
		//mes=ID +
		public Assignment getMesAssignment_13() { return cMesAssignment_13; }
		
		//ID
		public RuleCall getMesIDTerminalRuleCall_13_0() { return cMesIDTerminalRuleCall_13_0; }
		
		//"/"
		public Keyword getSolidusKeyword_14() { return cSolidusKeyword_14; }
		
		//ano=INT +
		public Assignment getAnoAssignment_15() { return cAnoAssignment_15; }
		
		//INT
		public RuleCall getAnoINTTerminalRuleCall_15_0() { return cAnoINTTerminalRuleCall_15_0; }
		
		//", Cargo Destinatario: "
		public Keyword getCargoDestinatarioKeyword_16() { return cCargoDestinatarioKeyword_16; }
		
		//cargoDestinatario=STRING +
		public Assignment getCargoDestinatarioAssignment_17() { return cCargoDestinatarioAssignment_17; }
		
		//STRING
		public RuleCall getCargoDestinatarioSTRINGTerminalRuleCall_17_0() { return cCargoDestinatarioSTRINGTerminalRuleCall_17_0; }
		
		//", Assunto: " +
		public Keyword getAssuntoKeyword_18() { return cAssuntoKeyword_18; }
		
		//assunto=STRING +
		public Assignment getAssuntoAssignment_19() { return cAssuntoAssignment_19; }
		
		//STRING
		public RuleCall getAssuntoSTRINGTerminalRuleCall_19_0() { return cAssuntoSTRINGTerminalRuleCall_19_0; }
		
		//", Destinos: " +
		public Keyword getDestinosKeyword_20() { return cDestinosKeyword_20; }
		
		//(destinos+=Destino*) +
		public Assignment getDestinosAssignment_21() { return cDestinosAssignment_21; }
		
		//Destino
		public RuleCall getDestinosDestinoParserRuleCall_21_0() { return cDestinosDestinoParserRuleCall_21_0; }
		
		//", Mensagem: " +
		public Keyword getMensagemKeyword_22() { return cMensagemKeyword_22; }
		
		//(paragrafos+=Paragrafo*) +
		public Assignment getParagrafosAssignment_23() { return cParagrafosAssignment_23; }
		
		//Paragrafo
		public RuleCall getParagrafosParagrafoParserRuleCall_23_0() { return cParagrafosParagrafoParserRuleCall_23_0; }
		
		//", Remetente: " +
		public Keyword getRemetenteKeyword_24() { return cRemetenteKeyword_24; }
		
		//remetente=STRING +
		public Assignment getRemetenteAssignment_25() { return cRemetenteAssignment_25; }
		
		//STRING
		public RuleCall getRemetenteSTRINGTerminalRuleCall_25_0() { return cRemetenteSTRINGTerminalRuleCall_25_0; }
		
		//", Cargo Remetente: " +
		public Keyword getCargoRemetenteKeyword_26() { return cCargoRemetenteKeyword_26; }
		
		//cargoRemetente=STRING
		public Assignment getCargoRemetenteAssignment_27() { return cCargoRemetenteAssignment_27; }
		
		//STRING
		public RuleCall getCargoRemetenteSTRINGTerminalRuleCall_27_0() { return cCargoRemetenteSTRINGTerminalRuleCall_27_0; }
	}
	public class DestinoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Memorando.Destino");
		private final Assignment cDestinoAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cDestinoIDTerminalRuleCall_0 = (RuleCall)cDestinoAssignment.eContents().get(0);
		
		//Destino:
		//    destino=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//destino=ID
		public Assignment getDestinoAssignment() { return cDestinoAssignment; }
		
		//ID
		public RuleCall getDestinoIDTerminalRuleCall_0() { return cDestinoIDTerminalRuleCall_0; }
	}
	public class ParagrafoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Memorando.Paragrafo");
		private final Assignment cParagrafoAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cParagrafoSTRINGTerminalRuleCall_0 = (RuleCall)cParagrafoAssignment.eContents().get(0);
		
		//Paragrafo:
		//    paragrafo=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//paragrafo=STRING
		public Assignment getParagrafoAssignment() { return cParagrafoAssignment; }
		
		//STRING
		public RuleCall getParagrafoSTRINGTerminalRuleCall_0() { return cParagrafoSTRINGTerminalRuleCall_0; }
	}
	
	
	private final ModelElements pModel;
	private final MemorandoElements pMemorando;
	private final DestinoElements pDestino;
	private final ParagrafoElements pParagrafo;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MemorandoGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pMemorando = new MemorandoElements();
		this.pDestino = new DestinoElements();
		this.pParagrafo = new ParagrafoElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.Memorando".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    memorandos+=Memorando*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Memorando:
	//    "Numero: " + numero=INT +
	//    ", Setor Destinatario: " + setorDestinatario=ID +
	//    ", Setor Remetente: " + setorRemetente=ID +
	//    ", Cidade: " cidade=ID +
	//    ", Estado: " estado=ID +
	//    ", Data: " dia=INT + "/" mes=ID + "/" ano=INT +
	//    ", Cargo Destinatario: " cargoDestinatario=STRING +
	//    ", Assunto: " + assunto=STRING +
	//    ", Destinos: " + (destinos+=Destino*) +
	//    ", Mensagem: " + (paragrafos+=Paragrafo*) +
	//    ", Remetente: " + remetente=STRING +
	//    ", Cargo Remetente: " + cargoRemetente=STRING;
	public MemorandoElements getMemorandoAccess() {
		return pMemorando;
	}
	
	public ParserRule getMemorandoRule() {
		return getMemorandoAccess().getRule();
	}
	
	//Destino:
	//    destino=ID;
	public DestinoElements getDestinoAccess() {
		return pDestino;
	}
	
	public ParserRule getDestinoRule() {
		return getDestinoAccess().getRule();
	}
	
	//Paragrafo:
	//    paragrafo=STRING;
	public ParagrafoElements getParagrafoAccess() {
		return pParagrafo;
	}
	
	public ParserRule getParagrafoRule() {
		return getParagrafoAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
