/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MemorandoGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Memorando.Model");
		private final Assignment cMemorandosAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cMemorandosMemorandoParserRuleCall_0 = (RuleCall)cMemorandosAssignment.eContents().get(0);
		
		//Model:
		//    memorandos+=Memorando*;
		@Override public ParserRule getRule() { return rule; }
		
		//memorandos+=Memorando*
		public Assignment getMemorandosAssignment() { return cMemorandosAssignment; }
		
		//Memorando
		public RuleCall getMemorandosMemorandoParserRuleCall_0() { return cMemorandosMemorandoParserRuleCall_0; }
	}
	public class MemorandoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Memorando.Memorando");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNumeroKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNumeroAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNumeroINTTerminalRuleCall_2_0 = (RuleCall)cNumeroAssignment_2.eContents().get(0);
		private final Keyword cSetorDestinatarioKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cSetorDestinatarioAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cSetorDestinatarioIDTerminalRuleCall_5_0 = (RuleCall)cSetorDestinatarioAssignment_5.eContents().get(0);
		private final Keyword cSetorRemetenteKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cColonKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cSetorRemetenteAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cSetorRemetenteIDTerminalRuleCall_8_0 = (RuleCall)cSetorRemetenteAssignment_8.eContents().get(0);
		private final Keyword cCidadeKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cColonKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cCidadeAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cCidadeIDTerminalRuleCall_11_0 = (RuleCall)cCidadeAssignment_11.eContents().get(0);
		private final Keyword cEstadoKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cColonKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cEstadoAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cEstadoIDTerminalRuleCall_14_0 = (RuleCall)cEstadoAssignment_14.eContents().get(0);
		private final Keyword cDataKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cColonKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cDiaAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cDiaINTTerminalRuleCall_17_0 = (RuleCall)cDiaAssignment_17.eContents().get(0);
		private final Keyword cSolidusKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Assignment cMesAssignment_19 = (Assignment)cGroup.eContents().get(19);
		private final RuleCall cMesIDTerminalRuleCall_19_0 = (RuleCall)cMesAssignment_19.eContents().get(0);
		private final Keyword cSolidusKeyword_20 = (Keyword)cGroup.eContents().get(20);
		private final Assignment cAnoAssignment_21 = (Assignment)cGroup.eContents().get(21);
		private final RuleCall cAnoINTTerminalRuleCall_21_0 = (RuleCall)cAnoAssignment_21.eContents().get(0);
		private final Keyword cCargoDestinatarioKeyword_22 = (Keyword)cGroup.eContents().get(22);
		private final Keyword cColonKeyword_23 = (Keyword)cGroup.eContents().get(23);
		private final Assignment cCargoDestinatarioAssignment_24 = (Assignment)cGroup.eContents().get(24);
		private final RuleCall cCargoDestinatarioSTRINGTerminalRuleCall_24_0 = (RuleCall)cCargoDestinatarioAssignment_24.eContents().get(0);
		private final Keyword cAssuntoKeyword_25 = (Keyword)cGroup.eContents().get(25);
		private final Keyword cColonKeyword_26 = (Keyword)cGroup.eContents().get(26);
		private final Assignment cAssuntoAssignment_27 = (Assignment)cGroup.eContents().get(27);
		private final RuleCall cAssuntoSTRINGTerminalRuleCall_27_0 = (RuleCall)cAssuntoAssignment_27.eContents().get(0);
		private final Keyword cDestinosKeyword_28 = (Keyword)cGroup.eContents().get(28);
		private final Keyword cColonKeyword_29 = (Keyword)cGroup.eContents().get(29);
		private final Keyword cLeftSquareBracketKeyword_30 = (Keyword)cGroup.eContents().get(30);
		private final Assignment cDestinosAssignment_31 = (Assignment)cGroup.eContents().get(31);
		private final RuleCall cDestinosDestinoParserRuleCall_31_0 = (RuleCall)cDestinosAssignment_31.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_32 = (Keyword)cGroup.eContents().get(32);
		private final Keyword cMensagemKeyword_33 = (Keyword)cGroup.eContents().get(33);
		private final Keyword cColonKeyword_34 = (Keyword)cGroup.eContents().get(34);
		private final Keyword cLeftSquareBracketKeyword_35 = (Keyword)cGroup.eContents().get(35);
		private final Assignment cParagrafosAssignment_36 = (Assignment)cGroup.eContents().get(36);
		private final RuleCall cParagrafosParagrafoParserRuleCall_36_0 = (RuleCall)cParagrafosAssignment_36.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_37 = (Keyword)cGroup.eContents().get(37);
		private final Keyword cRemetenteKeyword_38 = (Keyword)cGroup.eContents().get(38);
		private final Keyword cColonKeyword_39 = (Keyword)cGroup.eContents().get(39);
		private final Assignment cRemetenteAssignment_40 = (Assignment)cGroup.eContents().get(40);
		private final RuleCall cRemetenteSTRINGTerminalRuleCall_40_0 = (RuleCall)cRemetenteAssignment_40.eContents().get(0);
		private final Keyword cCargoRemetenteKeyword_41 = (Keyword)cGroup.eContents().get(41);
		private final Keyword cColonKeyword_42 = (Keyword)cGroup.eContents().get(42);
		private final Assignment cCargoRemetenteAssignment_43 = (Assignment)cGroup.eContents().get(43);
		private final RuleCall cCargoRemetenteSTRINGTerminalRuleCall_43_0 = (RuleCall)cCargoRemetenteAssignment_43.eContents().get(0);
		private final Keyword cSemicolonKeyword_44 = (Keyword)cGroup.eContents().get(44);
		
		//Memorando:
		//    "Numero" ':' numero=INT
		//    "Setor Destinatario" ':' setorDestinatario=ID
		//    "Setor Remetente" ':' setorRemetente=ID
		//    "Cidade" ':' cidade=ID
		//    "Estado" ':' estado=ID
		//    "Data" ':' dia=INT '/' mes=ID '/' ano=INT
		//    "Cargo Destinatario" ':' cargoDestinatario=STRING
		//    "Assunto" ':' assunto=STRING
		//    "Destinos" ':' '[' (destinos+=Destino*) ']'
		//    "Mensagem" ':' '[' (paragrafos+=Paragrafo*) ']'
		//    "Remetente" ':' remetente=STRING
		//    "Cargo Remetente" ':' cargoRemetente=STRING ';'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//"Numero" ':' numero=INT
		//"Setor Destinatario" ':' setorDestinatario=ID
		//"Setor Remetente" ':' setorRemetente=ID
		//"Cidade" ':' cidade=ID
		//"Estado" ':' estado=ID
		//"Data" ':' dia=INT '/' mes=ID '/' ano=INT
		//"Cargo Destinatario" ':' cargoDestinatario=STRING
		//"Assunto" ':' assunto=STRING
		//"Destinos" ':' '[' (destinos+=Destino*) ']'
		//"Mensagem" ':' '[' (paragrafos+=Paragrafo*) ']'
		//"Remetente" ':' remetente=STRING
		//"Cargo Remetente" ':' cargoRemetente=STRING ';'
		public Group getGroup() { return cGroup; }
		
		//"Numero"
		public Keyword getNumeroKeyword_0() { return cNumeroKeyword_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//numero=INT
		public Assignment getNumeroAssignment_2() { return cNumeroAssignment_2; }
		
		//INT
		public RuleCall getNumeroINTTerminalRuleCall_2_0() { return cNumeroINTTerminalRuleCall_2_0; }
		
		//"Setor Destinatario"
		public Keyword getSetorDestinatarioKeyword_3() { return cSetorDestinatarioKeyword_3; }
		
		//':'
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//setorDestinatario=ID
		public Assignment getSetorDestinatarioAssignment_5() { return cSetorDestinatarioAssignment_5; }
		
		//ID
		public RuleCall getSetorDestinatarioIDTerminalRuleCall_5_0() { return cSetorDestinatarioIDTerminalRuleCall_5_0; }
		
		//"Setor Remetente"
		public Keyword getSetorRemetenteKeyword_6() { return cSetorRemetenteKeyword_6; }
		
		//':'
		public Keyword getColonKeyword_7() { return cColonKeyword_7; }
		
		//setorRemetente=ID
		public Assignment getSetorRemetenteAssignment_8() { return cSetorRemetenteAssignment_8; }
		
		//ID
		public RuleCall getSetorRemetenteIDTerminalRuleCall_8_0() { return cSetorRemetenteIDTerminalRuleCall_8_0; }
		
		//"Cidade"
		public Keyword getCidadeKeyword_9() { return cCidadeKeyword_9; }
		
		//':'
		public Keyword getColonKeyword_10() { return cColonKeyword_10; }
		
		//cidade=ID
		public Assignment getCidadeAssignment_11() { return cCidadeAssignment_11; }
		
		//ID
		public RuleCall getCidadeIDTerminalRuleCall_11_0() { return cCidadeIDTerminalRuleCall_11_0; }
		
		//"Estado"
		public Keyword getEstadoKeyword_12() { return cEstadoKeyword_12; }
		
		//':'
		public Keyword getColonKeyword_13() { return cColonKeyword_13; }
		
		//estado=ID
		public Assignment getEstadoAssignment_14() { return cEstadoAssignment_14; }
		
		//ID
		public RuleCall getEstadoIDTerminalRuleCall_14_0() { return cEstadoIDTerminalRuleCall_14_0; }
		
		//"Data"
		public Keyword getDataKeyword_15() { return cDataKeyword_15; }
		
		//':'
		public Keyword getColonKeyword_16() { return cColonKeyword_16; }
		
		//dia=INT
		public Assignment getDiaAssignment_17() { return cDiaAssignment_17; }
		
		//INT
		public RuleCall getDiaINTTerminalRuleCall_17_0() { return cDiaINTTerminalRuleCall_17_0; }
		
		//'/'
		public Keyword getSolidusKeyword_18() { return cSolidusKeyword_18; }
		
		//mes=ID
		public Assignment getMesAssignment_19() { return cMesAssignment_19; }
		
		//ID
		public RuleCall getMesIDTerminalRuleCall_19_0() { return cMesIDTerminalRuleCall_19_0; }
		
		//'/'
		public Keyword getSolidusKeyword_20() { return cSolidusKeyword_20; }
		
		//ano=INT
		public Assignment getAnoAssignment_21() { return cAnoAssignment_21; }
		
		//INT
		public RuleCall getAnoINTTerminalRuleCall_21_0() { return cAnoINTTerminalRuleCall_21_0; }
		
		//"Cargo Destinatario"
		public Keyword getCargoDestinatarioKeyword_22() { return cCargoDestinatarioKeyword_22; }
		
		//':'
		public Keyword getColonKeyword_23() { return cColonKeyword_23; }
		
		//cargoDestinatario=STRING
		public Assignment getCargoDestinatarioAssignment_24() { return cCargoDestinatarioAssignment_24; }
		
		//STRING
		public RuleCall getCargoDestinatarioSTRINGTerminalRuleCall_24_0() { return cCargoDestinatarioSTRINGTerminalRuleCall_24_0; }
		
		//"Assunto"
		public Keyword getAssuntoKeyword_25() { return cAssuntoKeyword_25; }
		
		//':'
		public Keyword getColonKeyword_26() { return cColonKeyword_26; }
		
		//assunto=STRING
		public Assignment getAssuntoAssignment_27() { return cAssuntoAssignment_27; }
		
		//STRING
		public RuleCall getAssuntoSTRINGTerminalRuleCall_27_0() { return cAssuntoSTRINGTerminalRuleCall_27_0; }
		
		//"Destinos"
		public Keyword getDestinosKeyword_28() { return cDestinosKeyword_28; }
		
		//':'
		public Keyword getColonKeyword_29() { return cColonKeyword_29; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_30() { return cLeftSquareBracketKeyword_30; }
		
		//(destinos+=Destino*)
		public Assignment getDestinosAssignment_31() { return cDestinosAssignment_31; }
		
		//Destino
		public RuleCall getDestinosDestinoParserRuleCall_31_0() { return cDestinosDestinoParserRuleCall_31_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_32() { return cRightSquareBracketKeyword_32; }
		
		//"Mensagem"
		public Keyword getMensagemKeyword_33() { return cMensagemKeyword_33; }
		
		//':'
		public Keyword getColonKeyword_34() { return cColonKeyword_34; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_35() { return cLeftSquareBracketKeyword_35; }
		
		//(paragrafos+=Paragrafo*)
		public Assignment getParagrafosAssignment_36() { return cParagrafosAssignment_36; }
		
		//Paragrafo
		public RuleCall getParagrafosParagrafoParserRuleCall_36_0() { return cParagrafosParagrafoParserRuleCall_36_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_37() { return cRightSquareBracketKeyword_37; }
		
		//"Remetente"
		public Keyword getRemetenteKeyword_38() { return cRemetenteKeyword_38; }
		
		//':'
		public Keyword getColonKeyword_39() { return cColonKeyword_39; }
		
		//remetente=STRING
		public Assignment getRemetenteAssignment_40() { return cRemetenteAssignment_40; }
		
		//STRING
		public RuleCall getRemetenteSTRINGTerminalRuleCall_40_0() { return cRemetenteSTRINGTerminalRuleCall_40_0; }
		
		//"Cargo Remetente"
		public Keyword getCargoRemetenteKeyword_41() { return cCargoRemetenteKeyword_41; }
		
		//':'
		public Keyword getColonKeyword_42() { return cColonKeyword_42; }
		
		//cargoRemetente=STRING
		public Assignment getCargoRemetenteAssignment_43() { return cCargoRemetenteAssignment_43; }
		
		//STRING
		public RuleCall getCargoRemetenteSTRINGTerminalRuleCall_43_0() { return cCargoRemetenteSTRINGTerminalRuleCall_43_0; }
		
		//';'
		public Keyword getSemicolonKeyword_44() { return cSemicolonKeyword_44; }
	}
	public class DestinoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Memorando.Destino");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDestinoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDestinoIDTerminalRuleCall_0_0 = (RuleCall)cDestinoAssignment_0.eContents().get(0);
		private final Keyword cSpaceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Destino:
		//    destino=ID " "?;
		@Override public ParserRule getRule() { return rule; }
		
		//destino=ID " "?
		public Group getGroup() { return cGroup; }
		
		//destino=ID
		public Assignment getDestinoAssignment_0() { return cDestinoAssignment_0; }
		
		//ID
		public RuleCall getDestinoIDTerminalRuleCall_0_0() { return cDestinoIDTerminalRuleCall_0_0; }
		
		//" "?
		public Keyword getSpaceKeyword_1() { return cSpaceKeyword_1; }
	}
	public class ParagrafoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Memorando.Paragrafo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cParagrafoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cParagrafoSTRINGTerminalRuleCall_0_0 = (RuleCall)cParagrafoAssignment_0.eContents().get(0);
		private final Keyword cSpaceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Paragrafo:
		//    paragrafo=STRING " "?;
		@Override public ParserRule getRule() { return rule; }
		
		//paragrafo=STRING " "?
		public Group getGroup() { return cGroup; }
		
		//paragrafo=STRING
		public Assignment getParagrafoAssignment_0() { return cParagrafoAssignment_0; }
		
		//STRING
		public RuleCall getParagrafoSTRINGTerminalRuleCall_0_0() { return cParagrafoSTRINGTerminalRuleCall_0_0; }
		
		//" "?
		public Keyword getSpaceKeyword_1() { return cSpaceKeyword_1; }
	}
	
	
	private final ModelElements pModel;
	private final MemorandoElements pMemorando;
	private final DestinoElements pDestino;
	private final ParagrafoElements pParagrafo;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MemorandoGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pMemorando = new MemorandoElements();
		this.pDestino = new DestinoElements();
		this.pParagrafo = new ParagrafoElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.Memorando".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    memorandos+=Memorando*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Memorando:
	//    "Numero" ':' numero=INT
	//    "Setor Destinatario" ':' setorDestinatario=ID
	//    "Setor Remetente" ':' setorRemetente=ID
	//    "Cidade" ':' cidade=ID
	//    "Estado" ':' estado=ID
	//    "Data" ':' dia=INT '/' mes=ID '/' ano=INT
	//    "Cargo Destinatario" ':' cargoDestinatario=STRING
	//    "Assunto" ':' assunto=STRING
	//    "Destinos" ':' '[' (destinos+=Destino*) ']'
	//    "Mensagem" ':' '[' (paragrafos+=Paragrafo*) ']'
	//    "Remetente" ':' remetente=STRING
	//    "Cargo Remetente" ':' cargoRemetente=STRING ';'
	//    ;
	public MemorandoElements getMemorandoAccess() {
		return pMemorando;
	}
	
	public ParserRule getMemorandoRule() {
		return getMemorandoAccess().getRule();
	}
	
	//Destino:
	//    destino=ID " "?;
	public DestinoElements getDestinoAccess() {
		return pDestino;
	}
	
	public ParserRule getDestinoRule() {
		return getDestinoAccess().getRule();
	}
	
	//Paragrafo:
	//    paragrafo=STRING " "?;
	public ParagrafoElements getParagrafoAccess() {
		return pParagrafo;
	}
	
	public ParserRule getParagrafoRule() {
		return getParagrafoAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
