/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.mydsl.services.MemorandoGrammarAccess;

@SuppressWarnings("all")
public class MemorandoSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MemorandoGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Memorando_AssuntoKeyword_18_p;
	protected AbstractElementAlias match_Memorando_CargoRemetenteKeyword_26_p;
	protected AbstractElementAlias match_Memorando_DestinosKeyword_20_p;
	protected AbstractElementAlias match_Memorando_MensagemKeyword_22_p;
	protected AbstractElementAlias match_Memorando_NumeroKeyword_0_p;
	protected AbstractElementAlias match_Memorando_RemetenteKeyword_24_p;
	protected AbstractElementAlias match_Memorando_SetorDestinatarioKeyword_2_p;
	protected AbstractElementAlias match_Memorando_SetorRemetenteKeyword_4_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MemorandoGrammarAccess) access;
		match_Memorando_AssuntoKeyword_18_p = new TokenAlias(true, false, grammarAccess.getMemorandoAccess().getAssuntoKeyword_18());
		match_Memorando_CargoRemetenteKeyword_26_p = new TokenAlias(true, false, grammarAccess.getMemorandoAccess().getCargoRemetenteKeyword_26());
		match_Memorando_DestinosKeyword_20_p = new TokenAlias(true, false, grammarAccess.getMemorandoAccess().getDestinosKeyword_20());
		match_Memorando_MensagemKeyword_22_p = new TokenAlias(true, false, grammarAccess.getMemorandoAccess().getMensagemKeyword_22());
		match_Memorando_NumeroKeyword_0_p = new TokenAlias(true, false, grammarAccess.getMemorandoAccess().getNumeroKeyword_0());
		match_Memorando_RemetenteKeyword_24_p = new TokenAlias(true, false, grammarAccess.getMemorandoAccess().getRemetenteKeyword_24());
		match_Memorando_SetorDestinatarioKeyword_2_p = new TokenAlias(true, false, grammarAccess.getMemorandoAccess().getSetorDestinatarioKeyword_2());
		match_Memorando_SetorRemetenteKeyword_4_p = new TokenAlias(true, false, grammarAccess.getMemorandoAccess().getSetorRemetenteKeyword_4());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Memorando_AssuntoKeyword_18_p.equals(syntax))
				emit_Memorando_AssuntoKeyword_18_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Memorando_CargoRemetenteKeyword_26_p.equals(syntax))
				emit_Memorando_CargoRemetenteKeyword_26_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Memorando_DestinosKeyword_20_p.equals(syntax))
				emit_Memorando_DestinosKeyword_20_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Memorando_MensagemKeyword_22_p.equals(syntax))
				emit_Memorando_MensagemKeyword_22_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Memorando_NumeroKeyword_0_p.equals(syntax))
				emit_Memorando_NumeroKeyword_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Memorando_RemetenteKeyword_24_p.equals(syntax))
				emit_Memorando_RemetenteKeyword_24_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Memorando_SetorDestinatarioKeyword_2_p.equals(syntax))
				emit_Memorando_SetorDestinatarioKeyword_2_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Memorando_SetorRemetenteKeyword_4_p.equals(syntax))
				emit_Memorando_SetorRemetenteKeyword_4_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ', Assunto: '+
	 *
	 * This ambiguous syntax occurs at:
	 *     cargoDestinatario=STRING (ambiguity) assunto=STRING
	 */
	protected void emit_Memorando_AssuntoKeyword_18_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ', Cargo Remetente: '+
	 *
	 * This ambiguous syntax occurs at:
	 *     remetente=STRING (ambiguity) cargoRemetente=STRING
	 */
	protected void emit_Memorando_CargoRemetenteKeyword_26_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ', Destinos: '+
	 *
	 * This ambiguous syntax occurs at:
	 *     assunto=STRING (ambiguity) ', Mensagem: '+ ', Remetente: '+ remetente=STRING
	 *     assunto=STRING (ambiguity) ', Mensagem: '+ paragrafos+=Paragrafo
	 *     assunto=STRING (ambiguity) destinos+=Destino
	 */
	protected void emit_Memorando_DestinosKeyword_20_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ', Mensagem: '+
	 *
	 * This ambiguous syntax occurs at:
	 *     assunto=STRING ', Destinos: '+ (ambiguity) ', Remetente: '+ remetente=STRING
	 *     assunto=STRING ', Destinos: '+ (ambiguity) paragrafos+=Paragrafo
	 *     destinos+=Destino (ambiguity) ', Remetente: '+ remetente=STRING
	 *     destinos+=Destino (ambiguity) paragrafos+=Paragrafo
	 */
	protected void emit_Memorando_MensagemKeyword_22_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'Numero: '+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) numero=INT
	 */
	protected void emit_Memorando_NumeroKeyword_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ', Remetente: '+
	 *
	 * This ambiguous syntax occurs at:
	 *     assunto=STRING ', Destinos: '+ ', Mensagem: '+ (ambiguity) remetente=STRING
	 *     destinos+=Destino ', Mensagem: '+ (ambiguity) remetente=STRING
	 *     paragrafos+=Paragrafo (ambiguity) remetente=STRING
	 */
	protected void emit_Memorando_RemetenteKeyword_24_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ', Setor Destinatario: '+
	 *
	 * This ambiguous syntax occurs at:
	 *     numero=INT (ambiguity) setorDestinatario=ID
	 */
	protected void emit_Memorando_SetorDestinatarioKeyword_2_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ', Setor Remetente: '+
	 *
	 * This ambiguous syntax occurs at:
	 *     setorDestinatario=ID (ambiguity) setorRemetente=ID
	 */
	protected void emit_Memorando_SetorRemetenteKeyword_4_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
