/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.profissional.ui.internal.ProfissionalActivator;

public class ProfissionalUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ProfissionalActivator.getInstance().getInjector("org.xtext.example.mydsl.Profissional");
	}

}
